In [1]:
#env set-up
import pandas as pd
import spacy

nlp = spacy.load("en_core_web_sm")
pd.set_option("display.max_colwidth", 200)

In [2]:

df = pd.read_parquet("../data/raw/tscript-0000.parquet")
df.head()

,video_id,original_url,transcript
0,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,if you haven't followed us on any other thing this person's going through a lot with their hip we we spent a year basically running her hip into the ground so all your numbers are going to become ...

In [3]:
non_empty_df = df[df['transcript'].astype(bool)]

In [4]:
non_empty_df.head(10)

,video_id,original_url,transcript
0,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,if you haven't followed us on any other thing this person's going through a lot with their hip we we spent a year basically running her hip into the ground so all your numbers are going to become ...

Converting transcript blob into sentences

In [5]:
if "sentencizer" not in nlp.pipe_names:
    nlp.add_pipe("sentencizer")

sentence_rows = []

for idx, row in non_empty_df.iterrows():
    video_id = row["video_id"]
    url = row["original_url"]
    full_text = row["transcript"]

    doc = nlp(full_text)
    for sent in doc.sents:
        cleaned = sent.text.strip()
        if cleaned:
            sentence_rows.append({
                "video_id": video_id,
                "original_url": url,
                "transcript": cleaned
            })


clean_sent_df = pd.DataFrame(sentence_rows)
clean_sent_df = clean_sent_df[clean_sent_df['transcript'].str.len().between(30, 300)]

clean_sent_df.head()

video_id                                                                                                                                                                                                    Gt7pByYvr90
original_url                                                                                                                                                                https://www.youtube.com/watch?v=Gt7pByYvr90
transcript      if you haven't followed us on any other thing this person's going through a lot with their hip we we spent a year basically running her hip into the ground so all your numbers are going to become ...
Name: 0, dtype: object

,video_id,original_url,transcript
4,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,I think it's weird like deflected it but do you ever see like when somebody like falls down a Chasm and like a the Grand Canyon and the helicopter it's like two strings you're like on a gurney fly...
5,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,oh Mommy like the Dickens even being in the helicopter I think I would be scared I think it's scary because those p-town Cape Fear flights where I'm in the cockpit you
6,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,this is actually the flight attendant watch but inflation is the pilot Cape Air um exits and you know uh no phones
10,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,okay I slammed that Buckle into the thing I'm taking someone else's seat belt off putting it on me I'm like what are we talking about we're talking about passport and visas to Australia hey let's ...
12,Gt7pByYvr90,https://www.youtube.com/watch?v=Gt7pByYvr90,I thought we were doing High School freshman if you do not have a yellow binder you're in the wrong line Trixie Mattel